language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-voorhoede-front-end-guide' ]; then cd .. && eval "mv $currentfolder generator-voorhoede-front-end-guide" && cd generator-voorhoede-front-end-guide; fi

